### ISSUE TITLE
Tutorial 2.0

### ISSUE THREAD

**Issue by uranusjr** [uranusjr/django-tutorial-for-programmers#33]
* [x] 升到 Django 2.0
* [ ] Best practices
    * [x] Pipenv 管理專案套件
    * [x] Python Dotenv 管理環境變數 (#28)
    * [ ] Pytest 單元測試 (和它的一堆插件與使用技巧，例如 model mocking)
* [ ] 介紹一些 Model 與 Manager 的使用策略 (#24)
* [ ] 介紹 `{% include %}` tag (#17)
* [ ] 2017 年的 JavaScript solution 整合
    * 用 Webpack + Vue 當例子，但可以換成你自己想要的，重點是概念
* [ ] 有沒有其他的 API framework 選擇啊？實在不想用 Django REST Framework
    * 要不直接砍了那章，單純教怎麼手刻 API views 算了
        * Generic views
        * 自選 validation framework ([Pydantic](https://pydantic-docs.helpmanual.io) 很酷)
    * 如果你想要的是 SPA + API backend，那就不要用 Django
        * [API Star 有 Django integration](https://github.com/tomchristie/apistar#django-orm)
* [ ] Flexible Django
    * [ ] 解構 Django，讓你的專案不用 (完全) 遵循 Django 的規則
    * [ ] 最低限的 Django 專案 (拿掉所有不必要的東西)，再慢慢加回去，按你的想法規劃架構
    * [ ] 在非 Django 專案裡使用 Django 元件 (用 `settings.configure`)
